### ISSUE TITLE
Why do you use CIFF to export inverted index and use MaxScore query processing algorithm in PISA? 

### ISSUE THREAD

**Issue by namespace-Pt** [DI4IR/SIGIR2021#11]
In the original paper, you said
> We use Anserini to generate the inverted indexes of the collections. We then export the Anserini indexes using the CIFF common index file format, and process them with PISA using the MaxScore query processing algorithm.

As in this issue #7, you've said just quantize the scores, generate json files and use anserini. I expect this workflow is already a complete one, where I cannot find any code about exporting with CIFF and processing with PISA. Where do you use them? And why do you use them?

**Comment by amallia** [comment]
Take a look at this: https://github.com/DI4IR/dual-score
We are sharing all the data, so you can skip some steps.

**Comment by namespace-Pt** [comment]
Interesting. Thank you.
