### ISSUE TITLE
How to preprocess to get the deepimpact collection for custom evaluation on a dataset?

### ISSUE THREAD

**Issue by thakur-nandan** [DI4IR/SIGIR2021#12]
Hi, thanks for sharing this awesome deepimpact model.

We (@kwang2049) are coming up with a neural sparse toolkit and would like to provide support to the DeepImpact model for training and custom inference on any zero-shot test collection such as BEIR (https://github.com/UKPLab/beir). We were unable to figure out how the preprocessing of the collection was done to get the deepimpact terms? We also expand an MSMarco passage with top-40 questions from docT5query but don't know what to do after that. I believe this preprocessing is key for Deepimpact's optimal performance. 

For eg. We have an input passage (after top-40 docT5query queries appended):
``
The presence of communication amid scientific minds was equally important to the success of the Manhattan Project as scientific intellect was. The only cloud hanging over the impressive achievement of the atomic researchers and engineers is what their success truly meant; hundreds of thousands of innocent lives obliterated.\nwhat was important to the success of the manhattan project why was the manhattan project important? what was important about the manhattan project why was the success of the manhattan project so important? who was the manhattan project a scientific project for what was the manhattan project important for why was the manhattan project a success how was the success of the manhattan project why was the manhattan project important to the success of the project? what is the importance of communication amongst scientific minds what was the importance of scientific communication for the success of the manhattan project what was the purpose of the manhattan project why was the manhattan project significant? why was the manhattan project important why did scientists believe in atomic power why did scientists and engineers have to communicate? why was the manhattan project a success what was the purpose of the manhattan project why did scientists and engineers want to be involved in the manhattan project why are the scientists so valuable which of the following was an important outcome of the manhattan project? why was the manhattan project successful why was the manhattan project an important scientific achievement what was the success of manhattan what was the result of the manhattan project why was communications important to the success of the manhattan project? why the manhattan project was important why is it important to know who is the manhattan project what was the most important accomplishment to the success of the manhattan project? why was the manhattan project an important achievement? why was the manhattan project important to the success of the atomic bomb how did the manhattan project impact scientists? what were the effects of the manhattan project what were the results of the manhattan project and how did they affect the public what was the manhattan project why did scientists contribute to the success of the manhattan project why was communication important in the manhattan project what was the effect of the manhattan project on the world what was the importance of communication in the success of the manhattan project? why was communications important to the success of the manhattan project?\n
``

whereas the Deepimpact collection shows the same passage as:
``
The presence of communication amid scientific minds was equally important to the success of the Manhattan Project as scientific intellect was. The only cloud hanging over the impressive achievement of the atomic researchers and engineers is what their success truly meant; hundreds of thousands of innocent lives obliterated. [SEP] how be world are results public an have which it want result significant in were they communicate on amongst involved affect believe power impact successful importance scientists bomb contribute outcome why know effect so who effects about did for purpose valuable following most accomplishment a communications
``
Let us know if somehow this preprocessing script is available so that I convert zero-shot BEIR evaluation datasets in a similar fashion!

Kind Regards,
Nandan Thakur

**Comment by amallia** [comment]
Answered via email. Summary of the answer is that the passage is expanded with the set of unique new tokens coming from the predicted queries, that is the unique tokens that are part of the predicted queries and not part of the original document.

**Comment by arthur-75** [comment]
Hello I am attempting to submit a paper based on improving Spase methods and I am would like to have the processing code for DeepImpact from text to DeepImpact weights please.

**Comment by amallia** [comment]
Please refer to: https://github.com/basnetsoyuj/improving-learned-index

This is a newer version of DeepImpact named DeeperImpact.
