### ISSUE TITLE
Clarification about term and subterms

### ISSUE THREAD

**Issue by thibault-formal** [DI4IR/SIGIR2021#14]
Hi @amallia ,
From what I understood, in order to estimate the importance of a term, you consider the prediction of its first occurrence in the document (contrary to DeepCT which takes the max I think). It was not clear to me however (from the paper and the code) how you obtain the term-level prediction from sub-terms? Do you also consider the first occurrence? i.e. for indexes=['index', '##es'], you compute the score by simply scoring the 'index' embedding? 

Thanks in advance,
Thibault

**Comment by amallia** [comment]
Hi @thibault-formal 
> From what I understood, in order to estimate the importance of a term, you consider the prediction of its first occurrence in the document (contrary to DeepCT which takes the max I think)

Correct

> It was not clear to me however (from the paper and the code) how you obtain the term-level prediction from sub-terms?
>Do you also consider the first occurrence? 

Yes

**Comment by amallia** [comment]
I have a newer version of the code/model which performs these steps in a cleaner way. I am going to release the code soon. 

Closing now. Feel free to reopen if needed

**Comment by thibault-formal** [comment]
Perfect, thank you!
