### ISSUE TITLE
../../triples.train.small.expanded.tsv

### ISSUE THREAD

**Issue by cn-boop** [DI4IR/SIGIR2021#2]
can you open-source the training file of triples.train.small.expanded.tsv?
thanks
!!!!

**Comment by amallia** [comment]
Thanks for asking!

Training triples:
https://drive.google.com/file/d/1SlVfdqdtAjbf7T0tnaZ7As3esLf9s1TZ/view?usp=sharing

Expanded collection:
https://drive.google.com/file/d/10PKQeTsfxQclVlQs6dYDPyg6vaMR4cUX/view?usp=sharing

Model checkpoint:
https://drive.google.com/file/d/1WQJcgWI5NRNQz8aNrWFx72SqSaM2XskH/view?usp=sharing

**Comment by cn-boop** [comment]
thanks very much ---- Replied Message ----FromAntonio ***@***.***>Date07/22/2021 20:28 ***@***.***> ***@***.******@***.***>SubjectRe: [DI4IR/SIGIR2021] ../../triples.train.small.expanded.tsv (#2)
Thanks for asking!
Training triples:
https://drive.google.com/file/d/1SlVfdqdtAjbf7T0tnaZ7As3esLf9s1TZ/view?usp=sharing
Expanded collection:
https://drive.google.com/file/d/10PKQeTsfxQclVlQs6dYDPyg6vaMR4cUX/view?usp=sharing
Model checkpoint:
https://drive.google.com/file/d/1WQJcgWI5NRNQz8aNrWFx72SqSaM2XskH/view?usp=sharing

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/DI4IR/SIGIR2021/issues/2#issuecomment-884873397",
"url": "https://github.com/DI4IR/SIGIR2021/issues/2#issuecomment-884873397",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
