### ISSUE TITLE
about inject terms in the paper

### ISSUE THREAD

**Issue by cn-boop** [DI4IR/SIGIR2021#4]
Hello,
You write "For DocT5Query we use the predicted queries available on- line3, using 40 concatenated predictions for each passage in the corpus, as recommended by Nogueira and Lin " in your paper. 
I am wondering what is the exact meaning of 40?
40 words?
Thanks!!!!

**Comment by cn-boop** [comment]
Or can you release the code of how to get  collection-dT5q-newterms_unique.tsv?

**Comment by amallia** [comment]
A prediction is one query predicted by the docT5query model. So we use 40 queries per document. 

Of these queries we filter out the words that are already part of the original document and append only “new” words. 

Is now a bit more clear?

**Comment by cn-boop** [comment]
yeah thanks ---- Replied Message ----FromAntonio ***@***.***>Date07/28/2021 11:50 ***@***.***> ***@***.******@***.***>SubjectRe: [DI4IR/SIGIR2021] about inject terms in the paper (#4)

A prediction is one query predicted by the docT5query model. So we use 40 queries per document.

Of these queries we filter out the words that are already part of the original document and append only “new” words.

Is now a bit more clear?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/DI4IR/SIGIR2021/issues/4#issuecomment-887987648",

"url": "https://github.com/DI4IR/SIGIR2021/issues/4#issuecomment-887987648",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
