### ISSUE TITLE
About how to test?

### ISSUE THREAD

**Issue by cn-boop** [DI4IR/SIGIR2021#7]
Hi, there are no instructions about how to build index and retrieval. It seems that you don't use BM25 in pyserini tool. Just like "Since we quantized all the scores in the index in the same way, to compute a query-document score at query processing we can just sum up all the quantized scores of the document terms matching the query."
Can you give the instructions about how to get retrieval results and  build index? Thanks

**Comment by amallia** [comment]
Hello, thanks for asking this. I will definitely include it in the README.

Anyway here the steps you need to follow:
- run `scripts/quantize.py` to get the quantized version of the index
- run `scripts/convert_to_anserini.py` to convert into a file readable by Anserini 
- then follow: https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage-deepimpact.md
