### ISSUE TITLE
about model checkpoint

### ISSUE THREAD

**Issue by KinooYu** [DI4IR/SIGIR2021#8]
Hi,
Thanks for your excellent job. 
I have a question about **the given model checkpoint**(Model checkpoint: https://drive.google.com/file/d/1WQJcgWI5NRNQz8aNrWFx72SqSaM2XskH/view?usp=sharing).
When I loaded the checkpoint, there was an error that some keys missed and some were unexpected.  

Do you know how to solve it? 
<img width="1185" alt="截屏2021-09-03 下午4 10 05" src="https://user-images.githubusercontent.com/71424398/131973346-ad580e2e-a69e-4ebd-b4da-106bcdb371a0.png">

**Comment by amallia** [comment]
Hi, thanks for the question. 
The shared checkpoint was obtained using an old commit (https://github.com/DI4IR/SIGIR2021/tree/4e5d8414b074b411b30fcf389466bdce57112b56), then I have changed a bit the structure of the model (no differences in final results though).

Please try with this checkpoint and let me know: https://drive.google.com/file/d/17I2TWCB2hBSQ-E0Yt2sBEDH2z_rV0BN0/view?usp=sharing

**Comment by KinooYu** [comment]
Hi, there is only one unexpected key(**bert.embeddings.position_ids**) with the new checkpoint( https://drive.google.com/file/d/17I2TWCB2hBSQ-E0Yt2sBEDH2z_rV0BN0/view?usp=sharing)

<img width="517" alt="截屏2021-09-06 上午10 43 32" src="https://user-images.githubusercontent.com/71424398/132153339-c11733a0-8a70-4195-9f40-bd66edda745e.png">

**Comment by KinooYu** [comment]
Oh, I found a solution. Just update the transformers to 3.4.0 !
Thanks for your reply！
