### ISSUE TITLE
About network training

### ISSUE THREAD

**Issue by KinooYu** [DI4IR/SIGIR2021#9]
It seems that the the injected expansion terms from DocT5Query are not used during the deepImpact training process. Is that right?
<img width="1065" alt="截屏2021-09-28 上午1 05 41" src="https://user-images.githubusercontent.com/71424398/134954251-8b22da5c-293a-4bf0-963e-1293df92008b.png">

Thanks!

**Comment by amallia** [comment]
That is only the default value (if you dont pass any parameter). Make sure to pass the `--triples` parameter with expanded triples.

Also we can sync up offline if you need additional clarifications.

**Comment by KinooYu** [comment]
Thanks !
I just want to make sure the data used in the training process.
And could you please provide the training triples data ？

**Comment by amallia** [comment]
I added in the README:

https://drive.google.com/file/d/1SlVfdqdtAjbf7T0tnaZ7As3esLf9s1TZ/view?usp=sharing
